export enum BodyLocation {
  // Head & Neck
  HEAD = 'HEAD',
  FACE = 'FACE',
  NECK = 'NECK',

  // Trunk
  SHOULDER_LEFT = 'SHOULDER_LEFT',
  SHOULDER_RIGHT = 'SHOULDER_RIGHT',
  CHEST = 'CHEST',
  ABDOMEN = 'ABDOMEN',
  BACK_UPPER = 'BACK_UPPER',
  BACK_LOWER = 'BACK_LOWER',
  PELVIS = 'PELVIS',

  // Upper Limbs
  ARM_UPPER_LEFT = 'ARM_UPPER_LEFT',
  ARM_UPPER_RIGHT = 'ARM_UPPER_RIGHT',
  ELBOW_LEFT = 'ELBOW_LEFT',
  ELBOW_RIGHT = 'ELBOW_RIGHT',
  FOREARM_LEFT = 'FOREARM_LEFT',
  FOREARM_RIGHT = 'FOREARM_RIGHT',
  WRIST_LEFT = 'WRIST_LEFT',
  WRIST_RIGHT = 'WRIST_RIGHT',
  HAND_LEFT = 'HAND_LEFT',
  HAND_RIGHT = 'HAND_RIGHT',

  // Lower Limbs
  HIP_LEFT = 'HIP_LEFT',
  HIP_RIGHT = 'HIP_RIGHT',
  THIGH_LEFT = 'THIGH_LEFT',
  THIGH_RIGHT = 'THIGH_RIGHT',
  KNEE_LEFT = 'KNEE_LEFT',
  KNEE_RIGHT = 'KNEE_RIGHT',
  LEG_LOWER_LEFT = 'LEG_LOWER_LEFT',
  LEG_LOWER_RIGHT = 'LEG_LOWER_RIGHT',
  ANKLE_LEFT = 'ANKLE_LEFT',
  ANKLE_RIGHT = 'ANKLE_RIGHT',
  FOOT_LEFT = 'FOOT_LEFT',
  FOOT_RIGHT = 'FOOT_RIGHT',
}
