export enum CalendarEventType {
  APPOINTMENT = 'APPOINTMENT',
  PHYSIOTHERAPY = 'PHYSIOTHERAPY',
  NURSING_CARE = 'NURSING_CARE',
  BATH = 'BATH',
  MEAL = 'MEAL',
  ACTIVITY = 'ACTIVITY',
  OTHER = 'OTHER',
}
