export enum MeasurementType {
  BLOOD_PRESSURE_SYSTOLIC = 'BLOOD_PRESSURE_SYSTOLIC',
  BLOOD_PRESSURE_DIASTOLIC = 'BLOOD_PRESSURE_DIASTOLIC',
  HEART_RATE = 'HEART_RATE',
  WEIGHT = 'WEIGHT',
  HEIGHT = 'HEIGHT',
  BODY_TEMPERATURE = 'BODY_TEMPERATURE',
  BLOOD_GLUCOSE = 'BLOOD_GLUCOSE',
  OXYGEN_SATURATION = 'OXYGEN_SATURATION',
  BALANCE_SCORE = 'BALANCE_SCORE',
  MOBILITY_SCORE = 'MOBILITY_SCORE',
  COGNITIVE_SCORE = 'COGNITIVE_SCORE',
}